// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: recoto/recording/v1/recording.proto

package recordingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartFromURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFromURLRequest) Reset() {
	*x = StartFromURLRequest{}
	mi := &file_recoto_recording_v1_recording_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFromURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFromURLRequest) ProtoMessage() {}

func (x *StartFromURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recoto_recording_v1_recording_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFromURLRequest.ProtoReflect.Descriptor instead.
func (*StartFromURLRequest) Descriptor() ([]byte, []int) {
	return file_recoto_recording_v1_recording_proto_rawDescGZIP(), []int{0}
}

func (x *StartFromURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StartFromURLRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StartFromURLRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type StartFromURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordingId   string                 `protobuf:"bytes,1,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFromURLResponse) Reset() {
	*x = StartFromURLResponse{}
	mi := &file_recoto_recording_v1_recording_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFromURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFromURLResponse) ProtoMessage() {}

func (x *StartFromURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recoto_recording_v1_recording_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFromURLResponse.ProtoReflect.Descriptor instead.
func (*StartFromURLResponse) Descriptor() ([]byte, []int) {
	return file_recoto_recording_v1_recording_proto_rawDescGZIP(), []int{1}
}

func (x *StartFromURLResponse) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

var File_recoto_recording_v1_recording_proto protoreflect.FileDescriptor

const file_recoto_recording_v1_recording_proto_rawDesc = "" +
	"\n" +
	"#recoto/recording/v1/recording.proto\x12\x13recoto.recording.v1\x1a\x1egoogle/protobuf/duration.proto\"t\n" +
	"\x13StartFromURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\"9\n" +
	"\x14StartFromURLResponse\x12!\n" +
	"\frecording_id\x18\x01 \x01(\tR\vrecordingId2y\n" +
	"\x10RecordingService\x12e\n" +
	"\fStartFromURL\x12(.recoto.recording.v1.StartFromURLRequest\x1a).recoto.recording.v1.StartFromURLResponse\"\x00B\xdb\x01\n" +
	"\x17com.recoto.recording.v1B\x0eRecordingProtoP\x01ZBgithub.com/sun-yryr/recoto/pkg/api/recoto/recording/v1;recordingv1\xa2\x02\x03RRX\xaa\x02\x13Recoto.Recording.V1\xca\x02\x13Recoto\\Recording\\V1\xe2\x02\x1fRecoto\\Recording\\V1\\GPBMetadata\xea\x02\x15Recoto::Recording::V1b\x06proto3"

var (
	file_recoto_recording_v1_recording_proto_rawDescOnce sync.Once
	file_recoto_recording_v1_recording_proto_rawDescData []byte
)

func file_recoto_recording_v1_recording_proto_rawDescGZIP() []byte {
	file_recoto_recording_v1_recording_proto_rawDescOnce.Do(func() {
		file_recoto_recording_v1_recording_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recoto_recording_v1_recording_proto_rawDesc), len(file_recoto_recording_v1_recording_proto_rawDesc)))
	})
	return file_recoto_recording_v1_recording_proto_rawDescData
}

var file_recoto_recording_v1_recording_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recoto_recording_v1_recording_proto_goTypes = []any{
	(*StartFromURLRequest)(nil),  // 0: recoto.recording.v1.StartFromURLRequest
	(*StartFromURLResponse)(nil), // 1: recoto.recording.v1.StartFromURLResponse
	(*durationpb.Duration)(nil),  // 2: google.protobuf.Duration
}
var file_recoto_recording_v1_recording_proto_depIdxs = []int32{
	2, // 0: recoto.recording.v1.StartFromURLRequest.duration:type_name -> google.protobuf.Duration
	0, // 1: recoto.recording.v1.RecordingService.StartFromURL:input_type -> recoto.recording.v1.StartFromURLRequest
	1, // 2: recoto.recording.v1.RecordingService.StartFromURL:output_type -> recoto.recording.v1.StartFromURLResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recoto_recording_v1_recording_proto_init() }
func file_recoto_recording_v1_recording_proto_init() {
	if File_recoto_recording_v1_recording_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recoto_recording_v1_recording_proto_rawDesc), len(file_recoto_recording_v1_recording_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recoto_recording_v1_recording_proto_goTypes,
		DependencyIndexes: file_recoto_recording_v1_recording_proto_depIdxs,
		MessageInfos:      file_recoto_recording_v1_recording_proto_msgTypes,
	}.Build()
	File_recoto_recording_v1_recording_proto = out.File
	file_recoto_recording_v1_recording_proto_goTypes = nil
	file_recoto_recording_v1_recording_proto_depIdxs = nil
}
