version: "2"
linters:
  default: all
  disable:
    - depguard
    - tagalign # golinesのreformat-tagsと競合するため
    - exhaustruct
formatters:
  enable:
    - gofumpt
    - gci
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
