version: '3'
services:
  rec:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    tty: true
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=recadio
      - MYSQL_USER=recadio_user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
