# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
executors:
  default:
    machine:
      image: ubuntu-1604:202004-01
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: 
          name: apt install
          command: sudo rm /etc/apt/sources.list.d/circleci_trusty.list* && sudo apt update && sudo apt install -y ffmpeg rtmpdump
      - run: 
          name: pipenv install
          command: |
            python3 -m pip install --upgrade pip
            pip3 install pipenv
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            pipenv install
      - run: sudo apt install -y openvpn
      - run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          pipenv run python .circleci/decoder.py
      - run: |
          tar --no-same-permissions --no-same-owner -xvzf tmp.tar.gz
          mv config/* ./
          wget -qO- http://checkip.amazonaws.com | tee initial.ip
          sudo openvpn --config config.ovpn > openvpn.log 2>&1 &
          while [ -n "$(ip addr show tun0 2>&1 > /dev/null)" ]; do
            sleep 0.1;
          done
          cat openvpn.log
          wget -qO- http://checkip.amazonaws.com | tee final.ip
          if [ "$(cat initial.ip)" == "$(cat final.ip)" ]
          then
            echo "This computer's apparent public IP address was not different after connecting"
            echo "This may mean that your VPN is not configured correctly."
            exit 1
          fi
      - run:
          name: run test
          command: |
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            pipenv run test
