# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
executors:
  default:
    machine: true
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: 
          name: apt install
          command: sudo apt update && sudo apt install -y ffmpeg rtmpdump python3.6 python3.6-dev python3-pip curl
      - run: 
          name: pipenv install
          command: |
            python3 -m pip install --upgrade pip
            pip install pipenv
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            pipenv install
      - run: sudo apt install -y openvpn
      - run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          pipenv run python .circleci/decoder.py
      - run: |
          tar --no-same-permissions --no-same-owner -xvzf tmp.tar.gz
          mv config/* ./
          sudo openvpn --config config.ovpn > openvpn.log 2>&1 &
          while [ -n "$(ip addr show tun0 2>&1 > /dev/null)" ]; do
            sleep 0.1;
          done
          cat openvpn.log
      - run:
          name: check Grobal IP
          command: |
            curl https://env.b4iine.net/isp.php > res
            grep '<p class="main-txt">' res
      - run:
          name: run test
          command: |
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            pipenv run test
