# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: 
          name: apt install
          command: apt update && apt install -y ffmpeg rtmpdump python3.6 python3.6-dev python3-pip
      - run: 
          name: pipenv install
          command: |
            python3 -m pip install --upgrade pip
            pip install pipenv
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            pipenv install
      - run: apt install -y openvpn
      - run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          pipenv run python .circleci/decode.py
      - run: |
          tar -xvzf tmp.tar.gz
          mv config/* ./
          sudo -b openvpn --config config.ovpn
      - run: pipenv run test
