# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
executors:
  default:
    machine:
      image: ubuntu-1604:202004-01
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: 
          name: apt install
          command: sudo rm /etc/apt/sources.list.d/circleci_trusty.list* && sudo apt update && sudo apt install -y ffmpeg rtmpdump
      - run: 
          name: pipenv install
          command: |
            python3 -m pip install --upgrade pip
            pip3 install pipenv
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            pipenv install
      - run: sudo apt install -y openvpn
      - run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          pipenv run python .circleci/decoder.py
      - run: |
          tar --no-same-permissions --no-same-owner -xvzf tmp.tar.gz
          mv config/* ./
          # Connect to VPN
          sudo -b openvpn --config config.ovpn
          route
          curl https://env.b4iine.net/isp.php > res
      - run:
          name: check Grobal IP
          command: |
            grep '<p class="main-txt">' res
      - run:
          name: run test
          command: |
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            pipenv run test
