// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: recoto/health/v1/health.proto

package healthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_recoto_health_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recoto_health_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_recoto_health_v1_health_proto_rawDescGZIP(), []int{0}
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Results       []*CheckResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_recoto_health_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recoto_health_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_recoto_health_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckResponse) GetResults() []*CheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_recoto_health_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_recoto_health_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_recoto_health_v1_health_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CheckResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_recoto_health_v1_health_proto protoreflect.FileDescriptor

const file_recoto_health_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x1drecoto/health/v1/health.proto\x12\x10recoto.health.v1\"\x0e\n" +
	"\fCheckRequest\"`\n" +
	"\rCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x127\n" +
	"\aresults\x18\x02 \x03(\v2\x1d.recoto.health.v1.CheckResultR\aresults\"G\n" +
	"\vCheckResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok2[\n" +
	"\rHealthService\x12J\n" +
	"\x05Check\x12\x1e.recoto.health.v1.CheckRequest\x1a\x1f.recoto.health.v1.CheckResponse\"\x00B\xc3\x01\n" +
	"\x14com.recoto.health.v1B\vHealthProtoP\x01Z<github.com/sun-yryr/recoto/pkg/api/recoto/health/v1;healthv1\xa2\x02\x03RHX\xaa\x02\x10Recoto.Health.V1\xca\x02\x10Recoto\\Health\\V1\xe2\x02\x1cRecoto\\Health\\V1\\GPBMetadata\xea\x02\x12Recoto::Health::V1b\x06proto3"

var (
	file_recoto_health_v1_health_proto_rawDescOnce sync.Once
	file_recoto_health_v1_health_proto_rawDescData []byte
)

func file_recoto_health_v1_health_proto_rawDescGZIP() []byte {
	file_recoto_health_v1_health_proto_rawDescOnce.Do(func() {
		file_recoto_health_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recoto_health_v1_health_proto_rawDesc), len(file_recoto_health_v1_health_proto_rawDesc)))
	})
	return file_recoto_health_v1_health_proto_rawDescData
}

var file_recoto_health_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recoto_health_v1_health_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: recoto.health.v1.CheckRequest
	(*CheckResponse)(nil), // 1: recoto.health.v1.CheckResponse
	(*CheckResult)(nil),   // 2: recoto.health.v1.CheckResult
}
var file_recoto_health_v1_health_proto_depIdxs = []int32{
	2, // 0: recoto.health.v1.CheckResponse.results:type_name -> recoto.health.v1.CheckResult
	0, // 1: recoto.health.v1.HealthService.Check:input_type -> recoto.health.v1.CheckRequest
	1, // 2: recoto.health.v1.HealthService.Check:output_type -> recoto.health.v1.CheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recoto_health_v1_health_proto_init() }
func file_recoto_health_v1_health_proto_init() {
	if File_recoto_health_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recoto_health_v1_health_proto_rawDesc), len(file_recoto_health_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recoto_health_v1_health_proto_goTypes,
		DependencyIndexes: file_recoto_health_v1_health_proto_depIdxs,
		MessageInfos:      file_recoto_health_v1_health_proto_msgTypes,
	}.Build()
	File_recoto_health_v1_health_proto = out.File
	file_recoto_health_v1_health_proto_goTypes = nil
	file_recoto_health_v1_health_proto_depIdxs = nil
}
