name: auto-assign

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: endsWith(github.actor, '[bot]') == false && github.event.pull_request.assignee == null
    steps:
      - name: Assign
        run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
