name: Check Proto

on:
  push:
    branches:
      - v4
  pull_request:
    branches:
      - v4

permissions:
  contents: read
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          push: false
